
export const NEXT_JS = 'NextJS'
export const SERVER_ACTIONS = 'Server Actions'
export const RSC = 'RSC'
export const SSR = 'SSR'
export const SPA = 'SPA'
export const ROUTER = 'React Router'
export const LLM = "LLMs"
export const WEBPACK = 'Webpack'
export const ROLLUP = 'rollup '
export const GULP = 'Gulp '
export const BROCCOLI = 'Broccoli '
export const TELEGRAM = "Telegram API"
export const WHATSAPP= "WhatsApp API"
export const PWA = "PWA"
export const OPEN_AI = "OpenAI"
export const LANG_CHAIN = "langChain"
export const OLLAMA = "ollama"
export const SHADCN = "Shadcn"
export const CLOUDFLARE = "Cloudflare"
export const MISTRAL = "Mistral"
export const SUPABASE = "Supabase"
export const POSTGRES= "Postgres"
export const DDD = "Domain Driven Design"
export const GITHUB_ACTION = "Github Actions"
export const SNS = "AWS SNS"
export const EKS = "AWS EKS"
export const K8S = "K8S"
export const OT = "Open Telemetry"
export const BFF = "BFF"
export const ADVANCED_REACT = "Advanced ReactJS"
export const GQL = "GQL"
export const PROFILING ="Perf Profiling"
export const DESIGN_SYSTEM = "Design System"
export const EMOTION = "Emotion"
export const STORYBOOK = "Storybook"
export const AB_TESTING = "A/B testing"
export const GTM = "GTM"
export const HEXAGONAL = "Hexagonal Architecture"
export const CYPRESS = "Cypress"
export const TESTING_LIB = "Testing Library"
export const JEST = "Jest"
export const GRAFANA = "Grafana"
export const LOKI = "Loki"
export const PROMETHEUS = "Prometheus"
export const RABBITMQ = "RabbitMQ"
export const MONGO = "MongoDB"
export const MYSQL = "Mysql"
export const AWS = "AWS"
export const S3 = "AWS S3"
export const CF = "AWS CloudFront"
export const ALB = "AWS ALB"
export const ASG = "AWS ASG"
export const ARGO = "Argo"
export const HARBOR = "Harbor"
export const CUSTOMERIO = "Customer.io"
export const HOTJAR = "Hotjar"
export const IMG_PROXY = "Image Proxy"
export const NR = "New Relic"
export const T3 = "T3"
export const KNOCKOUT = "Knockout"
export const REACT = "ReactJS"
export const SSE = "Server Sent Events"
export const D3 = "D3 Charts"
export const WEBSOCKETS = "WebSockets"
export const WEB_WORKERS = "Web Workers"
export const TDD = "TDD"
export const CUCUMBER = "Cucumber"
export const GHERKINS = "Gherkin"
export const ANGULAR = "Angular 1"
export const SOCKETIO ="Socket.io"
export const BASH = "Bash Scripting"
export const CRON = "Cronjob"
export const BACKBONE = "Backbone"
export const JQUERY = "jQuery"
export const PYTHON = "Python"
export const DJANGO = "Django"
export const PYTEST = "PyTest"
export const LETTUCE = "Lettuce"


export const HIGH = 'high'
export const MID = 'mid'
export const LOW = 'low'